# Define base image
#FROM ubuntu
FROM octopuslabs/workertools:latest-ubuntu.2204

# Set base value for build argument
ARG LIQUIBASE_VERSION=4.25.1

# Prepare to install PowerShell
#RUN apt-get update && apt-get install wget apt-transport-https software-properties-common curl -y
#RUN wget -q "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
#RUN dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb

# Install PowerShell
#RUN apt-get update && apt-get install powershell unzip -y

# Download and install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
  && unzip awscliv2.zip \
  && rm awscliv2.zip \
  && ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

# Install Java
RUN apt-get update && apt-get install openjdk-17-jdk -y

# Download and install Liquibase
RUN curl -L https://github.com/liquibase/liquibase/releases/download/v${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}.zip -o liquibase.zip \
  && unzip liquibase.zip \
  && rm liquibase.zip

# Set environment variable to determine if in container
ENV IsContainer=true